### ISSUE TITLE
Accessing User Profile

### ISSUE THREAD

**Issue by ngurajeka** [auth0-community/auth0-go#17]
Hi, thanks for the great work.

Is this package has or will be provide a method to access / get `User Profile` when its authenticated?

Thanks

**Comment by yageek** [comment]
Could you be more precise about which information should be contained within the profile?

**Comment by maxekman** [comment]
The more up to date way of doing similar tasks is to use a Auth0 rule to enrich the access_token with specific filelds from the user profile, app_metadat or user_metadata. I think this is similar to what you want to do @ngurajeka, right?
