### ISSUE TITLE
Be context aware

### ISSUE THREAD

**Issue by ttjiaa** [auth0-community/auth0-go#32]
Pass and use `context` in various functions so that the work flow is context aware, to allow cancelation signals, deadlines, etc.

**Comment by beardaway** [comment]
Hey there @ttjiaa ! As of now, unfortunately nobody is actively maintaining this repo. Would you be able to contribute and implement the changes you suggested? We will be more than happy to review them! I'm closing this one but if you're interested in co-operating feel free to re-open it!
