### ISSUE TITLE
validator.Claims - Breaking API change

### ISSUE THREAD

**Issue by lukecyca** [auth0-community/auth0-go#62]
In #61 some breaking API changes were made (caused our CI builds to fail this morning) but it seems the documentation/examples were not also updated. I'm opening this issue to ensure the docs/examples are updated etc.

In particular, `validator.Claims(req, token, ...)` no longer takes the request as its first argument. From my quick reading of the PR, we can simply remove that argument from the call? I guess it never really needed the request to do its job?

@luna-duclos would you be able to open another PR that updates the example in the readme so we all can have a canonical example of how the library is to be used after your change?

Thanks!

**Comment by luna-duclos** [comment]
I missed the fact there were examples, apologies, will put up a PR on Monday
